### PR TITLE
Update fetch-configlet

### PR DESCRIPTION
**Pull request by jquorning**
Update fetch-configlet to latest upstream version from https://github.com/exercism/configlet/blob/master/scripts/fetch-configlet

### CODE REVIEW

**Review by ee7 — COMMENTED** [review]
Just updating with the latest upstream change.

**Review by ee7 — APPROVED** [review]

**Comment by ee7** [comment]
@jquorning I commented in https://github.com/exercism/ada/pull/6, but I don't have write access to this repo, sorry (otherwise I would've merged this).

Pinging @ErikSchierboom - let's merge?

Though I imagine sometime in the future all the repos will just use e.g. the `fetch-configlet` Github Action.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> Though I imagine sometime in the future all the repos will just use e.g. the `fetch-configlet` Github Action.

Well, they can do that for their CI, but tracks also want to run configlet locally, so there is still value in having the `fetch-configlet` script.

**Comment by ee7** [comment]
> so there is still value in having the fetch-configlet script.

Ah, okay.

**Pull request merged**
